### ISSUE TITLE
code.dlang not updated

### ISSUE THREAD

**Issue by o3o** [IrenejMarc/dpq#28]
Last  version on [code.dlang](http://code.dlang.org/packages/dpq) is not updated (v0.9.1), maybe the syntax of last tag is invalid.
You use `v.0.9.2`,   maybe it should be `v0.9.2`?

**Comment by IrenejMarc** [comment]
Thanks for notifying me, my bad. I'll create a new v0.9.3 tag with the latest changes

**Comment by o3o** [comment]
Now it's works: thank you for fix it and for your great library
