### ISSUE TITLE
Deprecation with dmd 2.096

### ISSUE THREAD

**Issue by o3o** [IrenejMarc/dpq#31]
```
Deprecation: function std.typecons.Nullable!int.Nullable.get_ is deprecated - Implicit conversion with alias Nullable.get this will be removed after 2.096. Please use .get explicitly.
```

**Comment by o3o** [comment]
Thank you Marc.
Can you update version please?

**Comment by IrenejMarc** [comment]
@o3o Would you like to be added as a collaborator on the project? I don’t have much time for maintaining the project, sadly.

**Comment by o3o** [comment]
I would be honored...
I don't know if I'm able to modify the sources because I don't have much experience in postgres ... anyway I can try
Thank you again
