### ISSUE TITLE
Noisy Writes to Stdout

### ISSUE THREAD

**Issue by mintyfresh** [IrenejMarc/dpq#35]
This commit seems to have added loose `writefln` statements in various places within the library:
https://github.com/IrenejMarc/dpq/commit/fb5200a0c2aed4fda4f7bb41edaa51f8f1415e8e

These look like they were probably added for debugging, as they don't provide particularly useful information.
If that's the case, would it be safe to remove them?

If they are intentional, it would be better to use a configurable logger instead.
That way, end users of the library can choose to suppress or redirect these messages.

The application I'm working on already has a mechanism for logging queries, and this just pollutes that output (especially since it writes to STDOUT when serializing time).

**Comment by o3o** [comment]
You're right, I will remove them

Thanks for the tip
