### ISSUE TITLE
_dpqLastConnection is not visible from module

### ISSUE THREAD

**Issue by Betelgeyser** [IrenejMarc/dpq#36]
When using `RelationMixin` compilation fails with an error:

```
../dpq/source/dpq/mixins.d(34,9): Error: module `dpq.connection` member `_dpqLastConnection` is not visible from module `app`
```

I guess this is because `_dpqLastConnection` has `package` visibility and thus fails to import to whatever relation you use.

Probably there should be some sort of public getter function to access `_dpqLastConnection` outside the package.

If this is fine I will probably implement a solution and make a pull request soon.

**Comment by Betelgeyser** [comment]
Since `_dpqLastConnection` is always references to the last created connection, I think this is a thread-unsafe and overall dangerous solution.

Considering this, probably instead of storing a reference to the last connection it would be better to have some global synchronized connection which is used by default if no connection is specified and must be created explicitly? Something like this:
```
DPQConnect("host=127.0.0.1 dbname=test user=test");
auto q = Query("SELECT 1");
auto r = q.run();
```

It doesn't really concerns the visibility issue per se, but they are related and both fixes may be implemented together.

Regarding connection being synchronized I believe this is more good than evil, since using a connection from multiple threads may be unsafe. To solve this a connection pool may be implemented in future.

**Comment by o3o** [comment]
Thank you
