### ISSUE TITLE
Can't specify a column as NonNullable

### ISSUE THREAD

**Issue by grogancolin** [IrenejMarc/dpq#8]
Example,
```
struct User{
   @PK @serial int id;
   string name; 
   @uniqueIndex string email;
}

db.ensureSchema!(User);
User u = User("TestName");
db.insert(u);
db.insert(u);
```

The above will insert two User entries, as even though email is a unique index, postgres won't complain as it's 'null' and therefore not checked against other values.
A @notNullable attribute would help I think, with dpq throwing before trying to send the data to postgres.

Or maybe I'm doing something wrong?

**Comment by IrenejMarc** [comment]
You're correct, there is currently no way to specify `NOT NULL` with dpq.

Implementing support for it through `@notNullable` or similar should not be an issue, but there is however, the issue of what values can actually be nullable according to D. Scalar values cannot be nullable and need to be specified so using the Nullable template, same goes for structs, but not classes or other heap-allocated resources.
Does this mean we should simply assume all D scalar values to be `NOT NULL`?

**Comment by grogancolin** [comment]
Yeah, that is an issue :-/ 
Making a 1 to 1 mapping between SQL and D is a tricky problem, hence I let people like you do it for me :-)

I was thinking however, of having a `@CustomConstraint()` UDA, that would be usable like:
```
struct myStruct{
   @PK @serial id;
   @CustomConstraint("NOT NULL") string email;
}
```
The constraint would be added with an `ALTER TABLE` call later (similar to how current constraints are added in your `ensureSchema` function).

I think that would allow the user to deal with situations like this.
I don't think it'd be overly hard to add either, hopefully I'll get time to experiment with it soon.

**Comment by katyukha** [comment]
Also @grogancolin's idea of CustomConstraint may help to deal with other SQL constraints like ```CHECK (price > 0)```, etc

**Comment by IrenejMarc** [comment]
I'll look into it in the coming days, thanks for the input. :)

**Comment by grogancolin** [comment]
Thanks @IrenejMarc !

**Comment by IrenejMarc** [comment]
v0.8.7 adds support for this https://github.com/IrenejMarc/dpq/releases/tag/v0.8.7

No full constraint support for now, since those would have to operate on a tables themselves, not columns and I can't think of a way to make that look nice right now :)
